### ISSUE TITLE
Required Timestamp as Paramter done by Library

### ISSUE THREAD

**Issue by kremsy** [larislackers/php-binance#3]
The Signed Routes all need a timestamp, would be good if this could be done by the lib itself.

I used `round(microtime(true) * 1000)` for my approach.

**Comment by ppapadatis** [comment]
As described here (https://www.binance.com/restapipub.html#timing-security) the timing security is implemented in application level. The application you are developing **MUST** be responsible for validating timestamps (**maybe in your application, the user would like to send a different timestamp, for previous or future transactions**).

The **timestamp** parameter (_which is documented thoroughly in the phpdoc blocks_) is not the only one required by the signed endpoints; you ought to validate the parameters yourself. **Have in mind, this is a library for rapid prototyping allowing you to access the Binance services, not a working application.**

And yes, the code you mentioned is a nice workaround. As you can see in the **tests** provided (https://github.com/larislackers/php-binance/blob/master/tests/BinanceApiContainerTest.php#L88) we have used the same thing (more or less) for the timestamp parameter.
