### ISSUE TITLE
error

### ISSUE THREAD

**Issue by newprogrammeram** [larislackers/php-binance#9]
require 'vendor/autoload.php';

// Get all orders for a symbol (BNB/BTC pair).
$orders = $bac->getOrderBook(['symbol' => 'BNBBTC']);
var_dump($orders->getBody()->getContents());

Notice: Undefined variable: bac in G:\xampp\htdocs\binance\index.php on line 6

Fatal error: Uncaught Error: Call to a member function getOrderBook() on null in G:\xampp\htdocs\binance\index.php:6 Stack trace: #0 {main} thrown in G:\xampp\htdocs\binance\index.php on line 6

**Comment by ppapadatis** [comment]
``` 
[...] in order to use the API wrapper you should initialize it with the aforementioned key and secret like this:
$bac = new BinanceApiContainer('<your_key>', '<your_secret>');
```

If you are unaware why you get the undefined variable error then:
1. Read the documentation again
2. Inspect your own code for error like this one (undefined variable means you are request a value from something that doesn't exist)
